language: java
branches:
  only:
    - master
  except:
    - dev
jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    - 52.59.145.37


before_install:
  - openssl aes-256-cbc -K $encrypted_1f212c0bd921_key -iv $encrypted_1f212c0bd921_iv -in training.pem.enc -out training.pem -d


after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 training.pem
  - ssh-add training.pem
  - scp target/*.jar -i training.pem $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - ssh -i training.pem $DEPLOY_USER@$DEPLOY_HOST "pkill -f \"java -jar\“"
  - ssh -i training.pem $DEPLOY_USER@$DEPLOY_HOST "java -jar $APPLICATION-$VERSION.jar"
