language: java

jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    - 52.59.145.37


before_install:
  - openssl aes-256-cbc -K $encrypted_1f212c0bd921_key -iv $encrypted_1f212c0bd921_iv -in training.pem.enc -out training.pem -d
  - cd webapp


after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $KEY_PATH
  - ssh-add $KEY_PATH
  - scp target/*.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - ssh  $DEPLOY_USER@$DEPLOY_HOST "pkill -f \"java -jar\""
  - ssh  $DEPLOY_USER@$DEPLOY_HOST "nohup java -jar $APPLICATION-$VERSION.jar > $APPLICATION-log.txt  2>&1&"
